/*
Copyright 2008-2011 Gephi
Authors : Ernesto Aneiros
Website : http://www.gephi.org

This file is part of Gephi.

Gephi is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

Gephi is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with Gephi.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.gephi.data.store.options;

import org.gephi.data.store.attributes.AttributeStore;
import org.openide.util.NbPreferences;
import static org.gephi.data.store.attributes.AttributeStore.*;

final class AdvancedPanel extends javax.swing.JPanel {

    private final AdvancedOptionsPanelController controller;

    AdvancedPanel(AdvancedOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bdbCacheSizeMsgLabel = new javax.swing.JLabel();
        bdbCacheSizeSlider = new javax.swing.JSlider();
        bdbCacheSizeLabel = new javax.swing.JLabel();
        bdbLogFileLabel = new javax.swing.JLabel();
        bdbLogFileSizeSpinner = new javax.swing.JSpinner();
        bdbLogFaultReadSizeLabel = new javax.swing.JLabel();
        bdbLogFaultReadSizeSpinner = new javax.swing.JSpinner();
        bdbLogIteratorReadSizeLabel = new javax.swing.JLabel();
        bdbLogIteratorReadSizeSpinner = new javax.swing.JSpinner();
        bdbLogTotalBufferSizeLabel = new javax.swing.JLabel();
        bdbTotalLogBufferSizeSpinner = new javax.swing.JSpinner();
        bdbLogNumBuffersLabel = new javax.swing.JLabel();
        bdbLogNumBuffersSpinner = new javax.swing.JSpinner();
        bdbShowStatsBtn = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(bdbCacheSizeMsgLabel, org.openide.util.NbBundle.getMessage(AdvancedPanel.class, "AdvancedPanel.bdbCacheSizeMsgLabel.text")); // NOI18N

        bdbCacheSizeSlider.setMinimum(5);
        bdbCacheSizeSlider.setMinorTickSpacing(5);
        bdbCacheSizeSlider.setPaintTicks(true);
        bdbCacheSizeSlider.setSnapToTicks(true);
        bdbCacheSizeSlider.setValue(10);

        org.openide.awt.Mnemonics.setLocalizedText(bdbCacheSizeLabel, org.openide.util.NbBundle.getMessage(AdvancedPanel.class, "AdvancedPanel.bdbCacheSizeLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(bdbLogFileLabel, org.openide.util.NbBundle.getMessage(AdvancedPanel.class, "AdvancedPanel.bdbLogFileLabel.text")); // NOI18N

        bdbLogFileSizeSpinner.setModel(new javax.swing.SpinnerNumberModel(20, 5, 150, 1));

        org.openide.awt.Mnemonics.setLocalizedText(bdbLogFaultReadSizeLabel, org.openide.util.NbBundle.getMessage(AdvancedPanel.class, "AdvancedPanel.bdbLogFaultReadSizeLabel.text")); // NOI18N

        bdbLogFaultReadSizeSpinner.setModel(new javax.swing.SpinnerNumberModel(5120, 512, 1048576, 1));

        org.openide.awt.Mnemonics.setLocalizedText(bdbLogIteratorReadSizeLabel, org.openide.util.NbBundle.getMessage(AdvancedPanel.class, "AdvancedPanel.bdbLogIteratorReadSizeLabel.text")); // NOI18N

        bdbLogIteratorReadSizeSpinner.setModel(new javax.swing.SpinnerNumberModel(16384, 512, 1048576, 1));

        org.openide.awt.Mnemonics.setLocalizedText(bdbLogTotalBufferSizeLabel, org.openide.util.NbBundle.getMessage(AdvancedPanel.class, "AdvancedPanel.bdbLogTotalBufferSizeLabel.text")); // NOI18N

        bdbTotalLogBufferSizeSpinner.setModel(new javax.swing.SpinnerNumberModel(12288, 512, 1048576, 1));

        org.openide.awt.Mnemonics.setLocalizedText(bdbLogNumBuffersLabel, org.openide.util.NbBundle.getMessage(AdvancedPanel.class, "AdvancedPanel.bdbLogNumBuffersLabel.text")); // NOI18N

        bdbLogNumBuffersSpinner.setModel(new javax.swing.SpinnerNumberModel(3, 1, 5, 1));

        org.openide.awt.Mnemonics.setLocalizedText(bdbShowStatsBtn, org.openide.util.NbBundle.getMessage(AdvancedPanel.class, "AdvancedPanel.bdbShowStatsBtn.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bdbCacheSizeMsgLabel)
                    .addComponent(bdbLogFileLabel)
                    .addComponent(bdbLogFaultReadSizeLabel)
                    .addComponent(bdbLogIteratorReadSizeLabel)
                    .addComponent(bdbLogTotalBufferSizeLabel)
                    .addComponent(bdbLogNumBuffersLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bdbLogNumBuffersSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bdbLogFileSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdbLogFaultReadSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdbLogIteratorReadSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdbCacheSizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdbTotalLogBufferSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bdbCacheSizeLabel)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(381, Short.MAX_VALUE)
                .addComponent(bdbShowStatsBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bdbCacheSizeMsgLabel)
                    .addComponent(bdbCacheSizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdbCacheSizeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bdbLogFileLabel)
                    .addComponent(bdbLogFileSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bdbLogFaultReadSizeLabel)
                    .addComponent(bdbLogFaultReadSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bdbLogIteratorReadSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdbLogIteratorReadSizeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bdbLogTotalBufferSizeLabel)
                    .addComponent(bdbTotalLogBufferSizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bdbLogNumBuffersLabel)
                    .addComponent(bdbLogNumBuffersSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(bdbShowStatsBtn)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bdbCacheSizeLabel, bdbCacheSizeMsgLabel, bdbCacheSizeSlider});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bdbLogFileLabel, bdbLogFileSizeSpinner});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bdbLogFaultReadSizeLabel, bdbLogFaultReadSizeSpinner});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bdbLogIteratorReadSizeLabel, bdbLogIteratorReadSizeSpinner});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bdbLogTotalBufferSizeLabel, bdbTotalLogBufferSizeSpinner});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bdbLogNumBuffersLabel, bdbLogNumBuffersSpinner});

    }// </editor-fold>//GEN-END:initComponents

    void load() {
        // Example:        
        // someCheckBox.setSelected(NbPreferences.forModule(AdvancedPanel.class).getBoolean("someFlag", false));
        int bdbMaxMemoryPercent = NbPreferences.forModule(AttributeStore.class).getInt(BDB_MAX_MEMORY_PERCENT, 10);
        int bdbLogFileSize = NbPreferences.forModule(AttributeStore.class).getInt(BDB_LOG_FILE_SIZE, 20);
        int bdbLogFaultReadSize = NbPreferences.forModule(AttributeStore.class).getInt(BDB_LOG_FAULT_READ_SIZE, 5120);
        int bdbLogIteratorReadSize = NbPreferences.forModule(AttributeStore.class).getInt(BDB_LOG_ITERATOR_READ_SIZE, 16384);
        int bdbTotalLogBufferSize = NbPreferences.forModule(AttributeStore.class).getInt(BDB_TOTAL_LOG_BUFFER_SIZE, 12288);
        int bdbLogNumBuffers = NbPreferences.forModule(AttributeStore.class).getInt(BDB_LOG_NUM_BUFFERS, 3);
        bdbCacheSizeSlider.setValue(bdbMaxMemoryPercent);
        bdbLogFileSizeSpinner.setValue(bdbLogFileSize);
        bdbLogFaultReadSizeSpinner.setValue(bdbLogFaultReadSize);
        bdbLogIteratorReadSizeSpinner.setValue(bdbLogIteratorReadSize);
        bdbTotalLogBufferSizeSpinner.setValue(bdbTotalLogBufferSize);
        bdbLogNumBuffersSpinner.setValue(bdbLogNumBuffers);
    }

    void store() {
        // Example:
        // NbPreferences.forModule(AdvancedPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        int bdbMaxMemoryPercent = bdbCacheSizeSlider.getValue();
        int bdbLogFileSize = (Integer)bdbLogFileSizeSpinner.getValue();
        int bdbLogFaultReadSize = (Integer)bdbLogFaultReadSizeSpinner.getValue();
        int bdbLogIteratorReadSize = (Integer)bdbLogIteratorReadSizeSpinner.getValue();
        int bdbTotalLogBufferSize = (Integer)bdbTotalLogBufferSizeSpinner.getValue();
        int bdbLogNumBuffers = (Integer)bdbLogNumBuffersSpinner.getValue();
        NbPreferences.forModule(AttributeStore.class).putInt(BDB_MAX_MEMORY_PERCENT, bdbMaxMemoryPercent);
        NbPreferences.forModule(AttributeStore.class).putInt(BDB_LOG_FILE_SIZE, bdbLogFileSize);
        NbPreferences.forModule(AttributeStore.class).putInt(BDB_LOG_FAULT_READ_SIZE, bdbLogFaultReadSize);
        NbPreferences.forModule(AttributeStore.class).putInt(BDB_LOG_ITERATOR_READ_SIZE, bdbLogIteratorReadSize);
        NbPreferences.forModule(AttributeStore.class).putInt(BDB_TOTAL_LOG_BUFFER_SIZE, bdbTotalLogBufferSize);
        NbPreferences.forModule(AttributeStore.class).putInt(BDB_LOG_NUM_BUFFERS, bdbLogNumBuffers);
    }

    boolean valid() {
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bdbCacheSizeLabel;
    private javax.swing.JLabel bdbCacheSizeMsgLabel;
    private javax.swing.JSlider bdbCacheSizeSlider;
    private javax.swing.JLabel bdbLogFaultReadSizeLabel;
    private javax.swing.JSpinner bdbLogFaultReadSizeSpinner;
    private javax.swing.JLabel bdbLogFileLabel;
    private javax.swing.JSpinner bdbLogFileSizeSpinner;
    private javax.swing.JLabel bdbLogIteratorReadSizeLabel;
    private javax.swing.JSpinner bdbLogIteratorReadSizeSpinner;
    private javax.swing.JLabel bdbLogNumBuffersLabel;
    private javax.swing.JSpinner bdbLogNumBuffersSpinner;
    private javax.swing.JLabel bdbLogTotalBufferSizeLabel;
    private javax.swing.JButton bdbShowStatsBtn;
    private javax.swing.JSpinner bdbTotalLogBufferSizeSpinner;
    // End of variables declaration//GEN-END:variables
}
