/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.gephi.visualization.view.profile.options;

import java.util.ArrayList;
import java.util.List;
import org.gephi.visualization.view.profile.VizProfile;
import org.gephi.visualization.view.profile.VizProfileSelector;

final class ProfilesPanel extends javax.swing.JPanel {

    private final ProfilesOptionsPanelController controller;
    private final List<VizProfileOptionPanel> panels;

    ProfilesPanel(ProfilesOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()

        VizProfile[] profiles = VizProfileSelector.profiles();
        
        this.panels = new ArrayList<VizProfileOptionPanel>();

        for (VizProfile p : profiles) {
            VizProfileOptionPanel optionPanel = p.optionPanel();
            this.panels.add(optionPanel);
            jTabbedPane1.addTab(p.name(), optionPanel);
        }

        this.controller.changed();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setLayout(new java.awt.GridBagLayout());

        jTabbedPane1.setDoubleBuffered(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jTabbedPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        for (VizProfileOptionPanel optionPanel : this.panels) {
            optionPanel.load();
        }
    }

    void store() {
        for (VizProfileOptionPanel optionPanel : this.panels) {
            optionPanel.store();
        }
    }

    boolean valid() {
        boolean result = true;
        for (VizProfileOptionPanel optionPanel : this.panels) {
            result &= optionPanel.valid();
        }
        return result;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
